/* Generated By:JavaCC: Do not edit this line. AnalizadorLexicoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorLexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PAGINA = 6;
  /** RegularExpression Id. */
  int TITULO = 7;
  /** RegularExpression Id. */
  int CONTENEDOR = 8;
  /** RegularExpression Id. */
  int FORMULARIO = 9;
  /** RegularExpression Id. */
  int CAMPOTEXTO = 10;
  /** RegularExpression Id. */
  int SELECTOR = 11;
  /** RegularExpression Id. */
  int BOTON = 12;
  /** RegularExpression Id. */
  int ID = 13;
  /** RegularExpression Id. */
  int ESTILO = 14;
  /** RegularExpression Id. */
  int FONDO = 15;
  /** RegularExpression Id. */
  int COLOR = 16;
  /** RegularExpression Id. */
  int FUENTE = 17;
  /** RegularExpression Id. */
  int TAMFUENTE = 18;
  /** RegularExpression Id. */
  int TEXTO = 19;
  /** RegularExpression Id. */
  int MUESTRA = 20;
  /** RegularExpression Id. */
  int VALOR = 21;
  /** RegularExpression Id. */
  int CANTIDAD = 22;
  /** RegularExpression Id. */
  int VALORINTERNO = 23;
  /** RegularExpression Id. */
  int VALOREXTERNO = 24;
  /** RegularExpression Id. */
  int SELECCIONADO = 25;
  /** RegularExpression Id. */
  int INICIO = 26;
  /** RegularExpression Id. */
  int FIN = 27;
  /** RegularExpression Id. */
  int TAMPX = 28;
  /** RegularExpression Id. */
  int SOLID = 29;
  /** RegularExpression Id. */
  int NUMCOLOR = 30;
  /** RegularExpression Id. */
  int NCOL = 31;
  /** RegularExpression Id. */
  int NUMERO = 32;
  /** RegularExpression Id. */
  int DIGIT = 33;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 34;
  /** RegularExpression Id. */
  int ASIGNACIONPUNTO = 35;
  /** RegularExpression Id. */
  int ASIGNACIONGUION = 36;
  /** RegularExpression Id. */
  int CONCATENACION = 37;
  /** RegularExpression Id. */
  int FINLINEA = 38;
  /** RegularExpression Id. */
  int CADENA = 39;
  /** RegularExpression Id. */
  int NOMBREARCHIVO = 40;
  /** RegularExpression Id. */
  int COMENTARIO = 41;
  /** RegularExpression Id. */
  int NEGRILLA = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"Pagina\"",
    "\"Titulo\"",
    "\"Contenedor\"",
    "\"Formulario\"",
    "\"CampoTexto\"",
    "\"Selector\"",
    "\"Boton\"",
    "\"id\"",
    "\"estilo\"",
    "\"fondo\"",
    "\"color\"",
    "\"fuente\"",
    "\"tamFuente\"",
    "\"texto\"",
    "\"muestra\"",
    "\"valor\"",
    "\"cantidad\"",
    "\"valorInterno\"",
    "\"valorExterno\"",
    "\"seleccionado\"",
    "\"-INICIO-\"",
    "\"-FIN-\"",
    "<TAMPX>",
    "\"solid\"",
    "<NUMCOLOR>",
    "<NCOL>",
    "<NUMERO>",
    "<DIGIT>",
    "<IDENTIFICADOR>",
    "\".\"",
    "<ASIGNACIONGUION>",
    "\"+\"",
    "\";\"",
    "<CADENA>",
    "<NOMBREARCHIVO>",
    "<COMENTARIO>",
    "<NEGRILLA>",
  };

}
