/* Generated By:JavaCC: Do not edit this line. AnalizadorLexicoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorLexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PAGINA = 8;
  /** RegularExpression Id. */
  int TITULO = 9;
  /** RegularExpression Id. */
  int CONTENEDOR = 10;
  /** RegularExpression Id. */
  int FORMULARIO = 11;
  /** RegularExpression Id. */
  int CAMPOTEXTO = 12;
  /** RegularExpression Id. */
  int SELECTOR = 13;
  /** RegularExpression Id. */
  int BOTON = 14;
  /** RegularExpression Id. */
  int ID = 15;
  /** RegularExpression Id. */
  int ESTILO = 16;
  /** RegularExpression Id. */
  int FONDO = 17;
  /** RegularExpression Id. */
  int COLOR = 18;
  /** RegularExpression Id. */
  int BORDE = 19;
  /** RegularExpression Id. */
  int FUENTE = 20;
  /** RegularExpression Id. */
  int TAMFUENTE = 21;
  /** RegularExpression Id. */
  int TEXTO = 22;
  /** RegularExpression Id. */
  int MUESTRA = 23;
  /** RegularExpression Id. */
  int VALOR = 24;
  /** RegularExpression Id. */
  int CANTIDAD = 25;
  /** RegularExpression Id. */
  int VALORINTERNO = 26;
  /** RegularExpression Id. */
  int VALOREXTERNO = 27;
  /** RegularExpression Id. */
  int SELECCIONADO = 28;
  /** RegularExpression Id. */
  int INICIO = 29;
  /** RegularExpression Id. */
  int FIN = 30;
  /** RegularExpression Id. */
  int TAMPX = 31;
  /** RegularExpression Id. */
  int SOLID = 32;
  /** RegularExpression Id. */
  int NUMCOLOR = 33;
  /** RegularExpression Id. */
  int NCOL = 34;
  /** RegularExpression Id. */
  int NUMERO = 35;
  /** RegularExpression Id. */
  int DIGIT = 36;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 37;
  /** RegularExpression Id. */
  int ASIGNACIONGUION = 38;
  /** RegularExpression Id. */
  int CONCATENACION = 39;
  /** RegularExpression Id. */
  int LLAMADOMET = 40;
  /** RegularExpression Id. */
  int DIVITEM = 41;
  /** RegularExpression Id. */
  int ININEGRILLA = 42;
  /** RegularExpression Id. */
  int FINNEGRILLA = 43;
  /** RegularExpression Id. */
  int NOMBREARCHIVO = 44;
  /** RegularExpression Id. */
  int CADENA = 45;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<token of kind 2>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\";\"",
    "\"Pagina\"",
    "\"Titulo\"",
    "\"Contenedor\"",
    "\"Formulario\"",
    "\"CampoTexto\"",
    "\"Selector\"",
    "\"Boton\"",
    "\"id\"",
    "\"estilo\"",
    "\"fondo\"",
    "\"color\"",
    "\"borde\"",
    "\"fuente\"",
    "\"tamFuente\"",
    "\"texto\"",
    "\"muestra\"",
    "\"valor\"",
    "\"cantidad\"",
    "\"valorInterno\"",
    "\"valorExterno\"",
    "\"seleccionado\"",
    "\"-INICIO-\"",
    "\"-FIN-\"",
    "<TAMPX>",
    "\"solid\"",
    "<NUMCOLOR>",
    "<NCOL>",
    "<NUMERO>",
    "<DIGIT>",
    "<IDENTIFICADOR>",
    "<ASIGNACIONGUION>",
    "\"+\"",
    "\".\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "<NOMBREARCHIVO>",
    "<CADENA>",
  };

}
